name: Build & Release Volcalypse

on:
  push:
    tags:
      - 'v*.*.*'  # tout tag commençant par v1.0.2, v1.0.3, etc.

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write  # suffit pour créer une Release

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      - name: Create Release and Upload JAR + Source
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/volcalypse-*.jar
            target/volcalypse-*-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
